//Daniel Akira Nakamura Gullich
package view;

import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import processamento.Imagem;

public class ProgramaGUI extends javax.swing.JFrame{

    private final JFileChooser escolherImagem;
    int i = 0;
    Imagem imagem;
    
    public ProgramaGUI() {
        initComponents();
        
        imagem = new Imagem();
        
        
        escolherImagem = new JFileChooser();
        escolherImagem.setCurrentDirectory(new File("."));// para escolher o diretorio
        escolherImagem.setFileSelectionMode(JFileChooser.FILES_ONLY);
        escolherImagem.addChoosableFileFilter(new FileNameExtensionFilter("*.jpeg", "jpeg") );
        escolherImagem.addChoosableFileFilter(new FileNameExtensionFilter("*.jpg", "jpg") );
        escolherImagem.addChoosableFileFilter(new FileNameExtensionFilter("*.png", "png") );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImagem = new javax.swing.JLabel();
        caminho = new javax.swing.JLabel();
        botaoEscolherImagem = new javax.swing.JButton();
        botaoDesfazer = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        painelGeral = new javax.swing.JPanel();
        painelInicio = new javax.swing.JPanel();
        painelCinza = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoCinzaSimples = new javax.swing.JButton();
        botaoCinzaPonderado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        painelThresholding = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botaoThresholding = new javax.swing.JButton();
        textoLimi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        painelNegativa = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        botaoNegativa = new javax.swing.JButton();
        painelSomaM = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        botaoSomaM = new javax.swing.JButton();
        botaoEscolherImagemSomaM = new javax.swing.JButton();
        caminhoSomaM = new javax.swing.JLabel();
        painelSomaP = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        botaoSomaP = new javax.swing.JButton();
        botaoEscolherImagemSomaP = new javax.swing.JButton();
        caminhoSomaP = new javax.swing.JLabel();
        textoSomaP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        painelSub = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        caminhoSub = new javax.swing.JLabel();
        botaoEscolherImagemSub = new javax.swing.JButton();
        botaoSub = new javax.swing.JButton();
        painelSaliente = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        botaoSaliente = new javax.swing.JButton();
        painelDilatacao = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        botaoDilatacao = new javax.swing.JButton();
        desativarD = new javax.swing.JCheckBox();
        painelErosao = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        botaoErosao = new javax.swing.JButton();
        desativarE = new javax.swing.JCheckBox();
        painelAF = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        botaoAbertura = new javax.swing.JButton();
        botaoFechamento = new javax.swing.JButton();
        desativarAF = new javax.swing.JCheckBox();
        painelRoberts = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        botaoRoberts = new javax.swing.JButton();
        panelSobel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        botaoSobel = new javax.swing.JButton();
        painelRobinson = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        botaoRobinson = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Processamento de Imagens");

        labelImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImagem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelImagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelImagem.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                labelImagemComponentResized(evt);
            }
        });

        caminho.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        caminho.setText("Nenhuma imagem escolhida");

        botaoEscolherImagem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoEscolherImagem.setText("Escolher Imagem...");
        botaoEscolherImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEscolherImagemActionPerformed(evt);
            }
        });

        botaoDesfazer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoDesfazer.setText("Desfazer");
        botaoDesfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesfazerActionPerformed(evt);
            }
        });

        botaoSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoSalvar.setText("Salvar Cópia");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        painelGeral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelGeral.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout painelInicioLayout = new javax.swing.GroupLayout(painelInicio);
        painelInicio.setLayout(painelInicioLayout);
        painelInicioLayout.setHorizontalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        painelInicioLayout.setVerticalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        painelGeral.add(painelInicio, "card3");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tons de cinza média e ponderada");

        botaoCinzaSimples.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCinzaSimples.setText("Aplicar");
        botaoCinzaSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCinzaSimplesActionPerformed(evt);
            }
        });

        botaoCinzaPonderado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCinzaPonderado.setText("Aplicar");
        botaoCinzaPonderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCinzaPonderadoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Simples:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ponderado:");

        javax.swing.GroupLayout painelCinzaLayout = new javax.swing.GroupLayout(painelCinza);
        painelCinza.setLayout(painelCinzaLayout);
        painelCinzaLayout.setHorizontalGroup(
            painelCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelCinzaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCinzaLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCinzaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(painelCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoCinzaPonderado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoCinzaSimples, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))))
        );
        painelCinzaLayout.setVerticalGroup(
            painelCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCinzaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(124, 124, 124)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCinzaSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCinzaPonderado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        painelGeral.add(painelCinza, "telaCinza");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thresholding");

        botaoThresholding.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoThresholding.setText("Aplicar");
        botaoThresholding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoThresholdingActionPerformed(evt);
            }
        });

        textoLimi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Limite (0.00 - 1.00):");

        javax.swing.GroupLayout painelThresholdingLayout = new javax.swing.GroupLayout(painelThresholding);
        painelThresholding.setLayout(painelThresholdingLayout);
        painelThresholdingLayout.setHorizontalGroup(
            painelThresholdingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelThresholdingLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(botaoThresholding, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelThresholdingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoLimi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        painelThresholdingLayout.setVerticalGroup(
            painelThresholdingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelThresholdingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(155, 155, 155)
                .addGroup(painelThresholdingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoLimi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(botaoThresholding, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        painelGeral.add(painelThresholding, "telaLimi");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Negativa");

        botaoNegativa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoNegativa.setText("Aplicar");
        botaoNegativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNegativaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelNegativaLayout = new javax.swing.GroupLayout(painelNegativa);
        painelNegativa.setLayout(painelNegativaLayout);
        painelNegativaLayout.setHorizontalGroup(
            painelNegativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelNegativaLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(botaoNegativa, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        painelNegativaLayout.setVerticalGroup(
            painelNegativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNegativaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(204, 204, 204)
                .addComponent(botaoNegativa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        painelGeral.add(painelNegativa, "telaNegativa");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Soma Média");

        botaoSomaM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoSomaM.setText("Aplicar");
        botaoSomaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSomaMActionPerformed(evt);
            }
        });

        botaoEscolherImagemSomaM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoEscolherImagemSomaM.setText("Escolher Imagem...");
        botaoEscolherImagemSomaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEscolherImagemSomaMActionPerformed(evt);
            }
        });

        caminhoSomaM.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        caminhoSomaM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caminhoSomaM.setText("Nenhuma imagem escolhida");

        javax.swing.GroupLayout painelSomaMLayout = new javax.swing.GroupLayout(painelSomaM);
        painelSomaM.setLayout(painelSomaMLayout);
        painelSomaMLayout.setHorizontalGroup(
            painelSomaMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
            .addGroup(painelSomaMLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(botaoSomaM, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSomaMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelSomaMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caminhoSomaM)
                    .addComponent(botaoEscolherImagemSomaM))
                .addGap(64, 64, 64))
        );
        painelSomaMLayout.setVerticalGroup(
            painelSomaMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSomaMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(59, 59, 59)
                .addComponent(caminhoSomaM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoEscolherImagemSomaM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(botaoSomaM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        painelGeral.add(painelSomaM, "telaSomaM");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Soma Ponderada");

        botaoSomaP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoSomaP.setText("Aplicar");
        botaoSomaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSomaPActionPerformed(evt);
            }
        });

        botaoEscolherImagemSomaP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoEscolherImagemSomaP.setText("Escolher Imagem...");
        botaoEscolherImagemSomaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEscolherImagemSomaPActionPerformed(evt);
            }
        });

        caminhoSomaP.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        caminhoSomaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caminhoSomaP.setText("Nenhuma imagem escolhida");

        textoSomaP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Limite da Imagem Principal:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("(0.00 - 1.00)");

        javax.swing.GroupLayout painelSomaPLayout = new javax.swing.GroupLayout(painelSomaP);
        painelSomaP.setLayout(painelSomaPLayout);
        painelSomaPLayout.setHorizontalGroup(
            painelSomaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelSomaPLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(botaoSomaP, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSomaPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelSomaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(caminhoSomaP)
                    .addComponent(botaoEscolherImagemSomaP))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSomaPLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSomaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoSomaP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelSomaPLayout.setVerticalGroup(
            painelSomaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSomaPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(59, 59, 59)
                .addComponent(caminhoSomaP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEscolherImagemSomaP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(painelSomaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSomaP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addComponent(botaoSomaP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        painelGeral.add(painelSomaP, "telaSomaP");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Subtração");

        caminhoSub.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        caminhoSub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caminhoSub.setText("Nenhuma imagem escolhida");

        botaoEscolherImagemSub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoEscolherImagemSub.setText("Escolher Imagem...");
        botaoEscolherImagemSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEscolherImagemSubActionPerformed(evt);
            }
        });

        botaoSub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoSub.setText("Aplicar");
        botaoSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelSubLayout = new javax.swing.GroupLayout(painelSub);
        painelSub.setLayout(painelSubLayout);
        painelSubLayout.setHorizontalGroup(
            painelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSubLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(painelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoEscolherImagemSub)
                    .addComponent(caminhoSub))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSubLayout.createSequentialGroup()
                .addGap(79, 80, Short.MAX_VALUE)
                .addComponent(botaoSub, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelSubLayout.setVerticalGroup(
            painelSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(59, 59, 59)
                .addComponent(caminhoSub, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoEscolherImagemSub, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(botaoSub, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        painelGeral.add(painelSub, "telaSub");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Pontos Salientes ");

        botaoSaliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoSaliente.setText("Aplicar");
        botaoSaliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelSalienteLayout = new javax.swing.GroupLayout(painelSaliente);
        painelSaliente.setLayout(painelSalienteLayout);
        painelSalienteLayout.setHorizontalGroup(
            painelSalienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSalienteLayout.createSequentialGroup()
                .addGroup(painelSalienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelSalienteLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(botaoSaliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelSalienteLayout.setVerticalGroup(
            painelSalienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSalienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(207, 207, 207)
                .addComponent(botaoSaliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        painelGeral.add(painelSaliente, "telaSaliente");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Dilatação");

        botaoDilatacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoDilatacao.setText("Aplicar");
        botaoDilatacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDilatacaoActionPerformed(evt);
            }
        });

        desativarD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        desativarD.setText("Desativar Thresholding (0.5)");

        javax.swing.GroupLayout painelDilatacaoLayout = new javax.swing.GroupLayout(painelDilatacao);
        painelDilatacao.setLayout(painelDilatacaoLayout);
        painelDilatacaoLayout.setHorizontalGroup(
            painelDilatacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDilatacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoDilatacao, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(painelDilatacaoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(desativarD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelDilatacaoLayout.setVerticalGroup(
            painelDilatacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDilatacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(136, 136, 136)
                .addComponent(desativarD)
                .addGap(39, 39, 39)
                .addComponent(botaoDilatacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        painelGeral.add(painelDilatacao, "telaDilatacao");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Erosão");

        botaoErosao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoErosao.setText("Aplicar");
        botaoErosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoErosaoActionPerformed(evt);
            }
        });

        desativarE.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        desativarE.setText("Desativar Thresholding (0.5)");

        javax.swing.GroupLayout painelErosaoLayout = new javax.swing.GroupLayout(painelErosao);
        painelErosao.setLayout(painelErosaoLayout);
        painelErosaoLayout.setHorizontalGroup(
            painelErosaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelErosaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelErosaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoErosao, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(painelErosaoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(desativarE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelErosaoLayout.setVerticalGroup(
            painelErosaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelErosaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(135, 135, 135)
                .addComponent(desativarE)
                .addGap(39, 39, 39)
                .addComponent(botaoErosao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        painelGeral.add(painelErosao, "telaErosao");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Abertura e Fechamento");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Abertura:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Fechamento:");

        botaoAbertura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoAbertura.setText("Aplicar");
        botaoAbertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAberturaActionPerformed(evt);
            }
        });

        botaoFechamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoFechamento.setText("Aplicar");
        botaoFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFechamentoActionPerformed(evt);
            }
        });

        desativarAF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        desativarAF.setText("Desativar Thresholding (0.5)");

        javax.swing.GroupLayout painelAFLayout = new javax.swing.GroupLayout(painelAF);
        painelAF.setLayout(painelAFLayout);
        painelAFLayout.setHorizontalGroup(
            painelAFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(painelAFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAFLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAFLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(painelAFLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(desativarAF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelAFLayout.setVerticalGroup(
            painelAFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(107, 107, 107)
                .addComponent(desativarAF)
                .addGap(31, 31, 31)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        painelGeral.add(painelAF, "telaAF");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Roberts");

        botaoRoberts.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoRoberts.setText("Aplicar");
        botaoRoberts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRobertsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelRobertsLayout = new javax.swing.GroupLayout(painelRoberts);
        painelRoberts.setLayout(painelRobertsLayout);
        painelRobertsLayout.setHorizontalGroup(
            painelRobertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
            .addGroup(painelRobertsLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(botaoRoberts, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelRobertsLayout.setVerticalGroup(
            painelRobertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRobertsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(203, 203, 203)
                .addComponent(botaoRoberts, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        painelGeral.add(painelRoberts, "telaRoberts");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Sobel");

        botaoSobel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoSobel.setText("Aplicar");
        botaoSobel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSobelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSobelLayout = new javax.swing.GroupLayout(panelSobel);
        panelSobel.setLayout(panelSobelLayout);
        panelSobelLayout.setHorizontalGroup(
            panelSobelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSobelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoSobel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        panelSobelLayout.setVerticalGroup(
            panelSobelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSobelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(203, 203, 203)
                .addComponent(botaoSobel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        painelGeral.add(panelSobel, "telaSobel");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Robinson");

        botaoRobinson.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoRobinson.setText("Aplicar");
        botaoRobinson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRobinsonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelRobinsonLayout = new javax.swing.GroupLayout(painelRobinson);
        painelRobinson.setLayout(painelRobinsonLayout);
        painelRobinsonLayout.setHorizontalGroup(
            painelRobinsonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRobinsonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoRobinson, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        painelRobinsonLayout.setVerticalGroup(
            painelRobinsonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRobinsonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(204, 204, 204)
                .addComponent(botaoRobinson, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        painelGeral.add(painelRobinson, "telaRobinson");

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu.setText("Processos");
        jMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Tons de cinza média e ponderada");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Thresholding");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Negativa");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setText("Soma Média");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setText("Soma Ponderada");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setText("Subtração");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setText("Pontos Salientes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem8.setText("Dilatação");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem9.setText("Erosão");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem10.setText("Abertura e Fechamento");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem11.setText("Roberts");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem12.setText("Sobel");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem13.setText("Robinson");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem13);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoEscolherImagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(caminho)
                        .addGap(0, 168, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoDesfazer, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEscolherImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caminho)
                    .addComponent(botaoDesfazer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(903, 672));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaCinza");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void botaoEscolherImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEscolherImagemActionPerformed
        int valorRetorno = escolherImagem.showOpenDialog(this);
        escolherImagem.setDialogTitle("Selecione a imagem");
        
        if(valorRetorno == JFileChooser.APPROVE_OPTION){
            try{
                imagem.setImagemOriginal(ImageIO.read(escolherImagem.getSelectedFile()));
                labelImagem.setIcon(resizeMaiores());
                caminho.setText("Nome: " + escolherImagem.getSelectedFile().getName());
            }catch(IOException e){
                caminho.setText("Nenhuma imagem escolhida");
                labelImagem.setIcon(null);
            }
        }else{
            caminho.setText("Nenhuma imagem escolhida");
            labelImagem.setIcon(null);
        }
        
    }//GEN-LAST:event_botaoEscolherImagemActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if(imagem.getImagemEditada() != null){
            int valorRetorno = escolherImagem.showSaveDialog(this);

            escolherImagem.setDialogTitle("Selecione o diretorio");

            if(valorRetorno == JFileChooser.APPROVE_OPTION){
                try {
                    ImageIO.write(imagem.getImagemEditada(), "jpg", new File(escolherImagem.getSelectedFile().getAbsolutePath()));
                } catch (IOException ex) {
                    System.out.println("Failed to save image!");
                }
            }
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoDesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesfazerActionPerformed
        if(imagem.getImagemEditada() != null){
            labelImagem.setIcon(null);
            imagem.restaurar();
            labelImagem.setIcon(resizeMaiores());
        }
    }//GEN-LAST:event_botaoDesfazerActionPerformed

    private void botaoCinzaSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCinzaSimplesActionPerformed
        if(imagem.getImagemEditada() != null){
            imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
            imagem.cinzaSimples();
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());    
        }
    }//GEN-LAST:event_botaoCinzaSimplesActionPerformed

    private void botaoCinzaPonderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCinzaPonderadoActionPerformed
        if(imagem.getImagemEditada() != null){
            imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
            imagem.cinzaPonderado();
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());    
        }
    }//GEN-LAST:event_botaoCinzaPonderadoActionPerformed

    private void botaoThresholdingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoThresholdingActionPerformed
        if(imagem.getImagemEditada() != null){
            imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
            imagem.limiarizacao(Double.parseDouble(textoLimi.getText()));
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        }
    }//GEN-LAST:event_botaoThresholdingActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaLimi");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaNegativa");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void botaoNegativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNegativaActionPerformed
        if(imagem.getImagemEditada() != null){
            imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
            imagem.negativa();
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        }
    }//GEN-LAST:event_botaoNegativaActionPerformed

    private void botaoSomaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSomaMActionPerformed
        if(imagem.getImagemEditada() != null && imagem.getImagemSomaM() != null){
            imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
            imagem.somaM();
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        }  
    }//GEN-LAST:event_botaoSomaMActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaSomaM");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void botaoEscolherImagemSomaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEscolherImagemSomaMActionPerformed
        
        int valorRetorno = escolherImagem.showOpenDialog(this);
        escolherImagem.setDialogTitle("Selecione a imagem");
        
        if(valorRetorno == JFileChooser.APPROVE_OPTION){
            try{
                imagem.setImagemSomaM(ImageIO.read(escolherImagem.getSelectedFile()));
                caminhoSomaM.setText("Nome: " + escolherImagem.getSelectedFile().getName());
            }catch(IOException e){
                caminhoSomaM.setText("Nenhuma imagem escolhida");
            }
        }else{
            caminhoSomaM.setText("Nenhuma imagem escolhida");
        }
        
    }//GEN-LAST:event_botaoEscolherImagemSomaMActionPerformed

    private void botaoSomaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSomaPActionPerformed
        if(imagem.getImagemEditada() != null && imagem.getImagemSomaP() != null){
            imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
            imagem.somaP(Double.parseDouble(textoSomaP.getText()));
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        }  
    }//GEN-LAST:event_botaoSomaPActionPerformed

    private void botaoEscolherImagemSomaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEscolherImagemSomaPActionPerformed
        int valorRetorno = escolherImagem.showOpenDialog(this);
        escolherImagem.setDialogTitle("Selecione a imagem");
        
        if(valorRetorno == JFileChooser.APPROVE_OPTION){
            try{
                imagem.setImagemSomaP(ImageIO.read(escolherImagem.getSelectedFile()));
                caminhoSomaP.setText("Nome: " + escolherImagem.getSelectedFile().getName());
            }catch(IOException e){
                caminhoSomaP.setText("Nenhuma imagem escolhida");
            }
        }else{
            caminhoSomaP.setText("Nenhuma imagem escolhida");
        }
    }//GEN-LAST:event_botaoEscolherImagemSomaPActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaSomaP");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void botaoEscolherImagemSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEscolherImagemSubActionPerformed
        int valorRetorno = escolherImagem.showOpenDialog(this);
        escolherImagem.setDialogTitle("Selecione a imagem");
        
        if(valorRetorno == JFileChooser.APPROVE_OPTION){
            try{
                imagem.setImagemSub(ImageIO.read(escolherImagem.getSelectedFile()));
                caminhoSub.setText("Nome: " + escolherImagem.getSelectedFile().getName());
            }catch(IOException e){
                caminhoSub.setText("Nenhuma imagem escolhida");
            }
        }else{
            caminhoSub.setText("Nenhuma imagem escolhida");
        }
    }//GEN-LAST:event_botaoEscolherImagemSubActionPerformed

    private void botaoSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSubActionPerformed
        if(imagem.getImagemEditada() != null){
            imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
            imagem.sub();
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        }  
    }//GEN-LAST:event_botaoSubActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaSub");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void botaoSalienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalienteActionPerformed
        if(imagem.getImagemEditada() != null){
            imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
            imagem.saliente();
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        } 
    }//GEN-LAST:event_botaoSalienteActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaSaliente");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaDilatacao");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void labelImagemComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_labelImagemComponentResized
        if(imagem.getImagemEditada() != null){
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        } 
    }//GEN-LAST:event_labelImagemComponentResized

    private void botaoDilatacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDilatacaoActionPerformed
        if(imagem.getImagemEditada() != null){
            
            if(!desativarD.isSelected()){
                imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
                imagem.limiarizacao(0.5);
                imagem.setImagemEditada(imagem.dilatacao(imagem.getImagemEditada()));
            }
            else{
                imagem.setImagemEditada(imagem.dilatacao(imagem.getImagemOriginal()));
            }
            
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        } 
    }//GEN-LAST:event_botaoDilatacaoActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaErosao");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void botaoErosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoErosaoActionPerformed
        if(imagem.getImagemEditada() != null){
            if(!desativarE.isSelected()){
                imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
                imagem.limiarizacao(0.5);
                imagem.setImagemEditada(imagem.erosao(imagem.getImagemEditada()));
            }
            else{
                imagem.setImagemEditada(imagem.erosao(imagem.getImagemOriginal()));
            }
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        } 
    }//GEN-LAST:event_botaoErosaoActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaAF");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void botaoAberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAberturaActionPerformed
        if(imagem.getImagemEditada() != null){
            if(!desativarAF.isSelected()){
                imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
                imagem.limiarizacao(0.5);
                imagem.setImagemEditada(imagem.dilatacao(imagem.erosao(imagem.getImagemEditada())));
            }else{
                imagem.setImagemEditada(imagem.dilatacao(imagem.erosao(imagem.getImagemOriginal())));
            }
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        } 
    }//GEN-LAST:event_botaoAberturaActionPerformed

    private void botaoFechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFechamentoActionPerformed
        if(imagem.getImagemEditada() != null){ 
            if(!desativarAF.isSelected()){
                imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
                imagem.limiarizacao(0.5);
                imagem.setImagemEditada(imagem.erosao(imagem.dilatacao(imagem.getImagemEditada())));
            }
            else{
                imagem.setImagemEditada(imagem.erosao(imagem.dilatacao(imagem.getImagemOriginal())));
            }
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        } 
    }//GEN-LAST:event_botaoFechamentoActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaRoberts");
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void botaoRobertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRobertsActionPerformed
        if(imagem.getImagemEditada() != null){
            imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
            imagem.roberts();
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        } 
    }//GEN-LAST:event_botaoRobertsActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaSobel");
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void botaoSobelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSobelActionPerformed
        if(imagem.getImagemEditada() != null){
            imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
            imagem.sobel();
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        } 
    }//GEN-LAST:event_botaoSobelActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        CardLayout cl = (CardLayout) painelGeral.getLayout();
        cl.show(painelGeral, "telaRobinson");
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void botaoRobinsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRobinsonActionPerformed
        if(imagem.getImagemEditada() != null){
            imagem.criarNovaImagem(imagem.getImagemOriginal().getWidth(),imagem.getImagemOriginal().getHeight());
            imagem.robinson();
            labelImagem.setIcon(null);
            labelImagem.setIcon(resizeMaiores());
        } 
    }//GEN-LAST:event_botaoRobinsonActionPerformed

    public void iniciar(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    public ImageIcon resizeMaiores(){
        double scalax = (double) (labelImagem.getWidth()-15) / imagem.getImagemEditada().getWidth() ;
        double scalay = (double) (labelImagem.getHeight()-15) / imagem.getImagemEditada().getHeight() ;
        double resultado = Math.min(scalax, scalay);
       
            return new ImageIcon(imagem.getImagemEditada().getScaledInstance((int) (imagem.getImagemEditada().getWidth() * resultado), (int) (imagem.getImagemEditada().getHeight() * resultado), Image.SCALE_SMOOTH));
            
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAbertura;
    private javax.swing.JButton botaoCinzaPonderado;
    private javax.swing.JButton botaoCinzaSimples;
    private javax.swing.JButton botaoDesfazer;
    private javax.swing.JButton botaoDilatacao;
    private javax.swing.JButton botaoErosao;
    private javax.swing.JButton botaoEscolherImagem;
    private javax.swing.JButton botaoEscolherImagemSomaM;
    private javax.swing.JButton botaoEscolherImagemSomaP;
    private javax.swing.JButton botaoEscolherImagemSub;
    private javax.swing.JButton botaoFechamento;
    private javax.swing.JButton botaoNegativa;
    private javax.swing.JButton botaoRoberts;
    private javax.swing.JButton botaoRobinson;
    private javax.swing.JButton botaoSaliente;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoSobel;
    private javax.swing.JButton botaoSomaM;
    private javax.swing.JButton botaoSomaP;
    private javax.swing.JButton botaoSub;
    private javax.swing.JButton botaoThresholding;
    private javax.swing.JLabel caminho;
    private javax.swing.JLabel caminhoSomaM;
    private javax.swing.JLabel caminhoSomaP;
    private javax.swing.JLabel caminhoSub;
    private javax.swing.JCheckBox desativarAF;
    private javax.swing.JCheckBox desativarD;
    private javax.swing.JCheckBox desativarE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JPanel painelAF;
    private javax.swing.JPanel painelCinza;
    private javax.swing.JPanel painelDilatacao;
    private javax.swing.JPanel painelErosao;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JPanel painelInicio;
    private javax.swing.JPanel painelNegativa;
    private javax.swing.JPanel painelRoberts;
    private javax.swing.JPanel painelRobinson;
    private javax.swing.JPanel painelSaliente;
    private javax.swing.JPanel painelSomaM;
    private javax.swing.JPanel painelSomaP;
    private javax.swing.JPanel painelSub;
    private javax.swing.JPanel painelThresholding;
    private javax.swing.JPanel panelSobel;
    private javax.swing.JTextField textoLimi;
    private javax.swing.JTextField textoSomaP;
    // End of variables declaration//GEN-END:variables

}
